Add express ci jobs

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -7,10 +7,12 @@ jobs:
     working_directory: ~/app
     steps:
       - checkout
+      - attach_workspace:
+          at: ~/app
       - restore_cache:
           keys:
-          - v1-dependencies-{{ checksum "tilup-web/package.json" }}
-          - v1-dependencies-
+          - v1-dependencies-web-{{ checksum "tilup-web/package.json" }}
+          - v1-dependencies-web-
       - run:
           name: npm install
           command: |
@@ -20,7 +22,7 @@ jobs:
       - save_cache:
           paths:
             - tilup-web/node_modules
-          key: v1-dependencies-{{ checksum "tilup-web/package.json" }}
+          key: v1-dependencies-web-{{ checksum "tilup-web/package.json" }}
       - persist_to_workspace:
           root: .
           paths: .
@@ -52,155 +54,207 @@ jobs:
             npm run test
 
   react_build:
-      docker:
-        - image: circleci/node:7.10
-      working_directory: ~/app
-      steps:
-        - attach_workspace:
-            at: ~/app
-        - run:
-            name: Run build
-            command: |
-              cd tilup-web
-              CI=false npm run build
+    docker:
+      - image: circleci/node:7.10
+    working_directory: ~/app
+    steps:
+      - attach_workspace:
+          at: ~/app
+      - run:
+          name: Run build
+          command: |
+            cd tilup-web
+            CI=false npm run build
+
+  express_install_dependencies:
+    docker:
+      - image: circleci/node:7.10
+    working_directory: ~/app
+    steps:
+      - checkout
+      - attach_workspace:
+          at: ~/app
+      - restore_cache:
+          keys:
+          - v1-dependencies-server-{{ checksum "tilup-server/package.json" }}
+          - v1-dependencies-server-
+      - run:
+          name: npm install
+          command: |
+            cd tilup-server
+            npm install
+
+      - save_cache:
+          paths:
+            - tilup-server/node_modules
+          key: v1-dependencies-server-{{ checksum "tilup-server/package.json" }}
+      - persist_to_workspace:
+          root: .
+          paths: .
+
+  express_lint_checks:
+    docker:
+      - image: circleci/node:7.10
+    working_directory: ~/app
+    steps:
+      - attach_workspace:
+          at: ~/app
+      - run:
+          name: Run lint checks
+          command: |
+            cd tilup-server
+            npm run lint
+
+  express_tests:
+    docker:
+      - image: circleci/node:7.10
+    working_directory: ~/app
+    steps:
+      - attach_workspace:
+          at: ~/app
+      - run:
+          name: Run tests
+          command: |
+            cd tilup-server
+            npm run test
 
   docker_build_and_push:
-      docker:
-        - image: circleci/node:7.10
-      working_directory: ~/app
-      steps:
-        - attach_workspace:
-            at: ~/app
-        - setup_remote_docker:
-            docker_layer_caching: true
-        - run:
-           name: Docker build
-           command: |
-             docker build -t todayilearned .
+    docker:
+      - image: circleci/node:7.10
+    working_directory: ~/app
+    steps:
+      - attach_workspace:
+          at: ~/app
+      - setup_remote_docker:
+          docker_layer_caching: true
+      - run:
+         name: Docker build
+         command: |
+           docker build -t todayilearned .
 
-        - run:
-           name: Docker environment variables check
-           command: |
-             echo Docker environment variables check
-             NUM_OF_VARIABLES_TO_CHECK=2
-             VARIABLES_TO_CHECK=(\
-             $CI_DOCKER_PASSWORD \
-             $CI_DOCKER_USER \
-             )
+      - run:
+         name: Docker environment variables check
+         command: |
+           echo Docker environment variables check
+           NUM_OF_VARIABLES_TO_CHECK=2
+           VARIABLES_TO_CHECK=(\
+           $CI_DOCKER_PASSWORD \
+           $CI_DOCKER_USER \
+           )
 
-             if [ $NUM_OF_VARIABLES_TO_CHECK -ne ${#VARIABLES_TO_CHECK[@]} ]
-             then
-               echo "  "Add Environment Variables on ci environment.
-               echo "  "Number of variables. Expected $NUM_OF_VARIABLES_TO_CHECK, Actual ${#VARIABLES_TO_CHECK[@]}
-               echo "  "CI_DOCKER_USER CI_DOCKER_PASSWORD required.
-               exit 1
-             fi
+           if [ $NUM_OF_VARIABLES_TO_CHECK -ne ${#VARIABLES_TO_CHECK[@]} ]
+           then
+             echo "  "Add Environment Variables on ci environment.
+             echo "  "Number of variables. Expected $NUM_OF_VARIABLES_TO_CHECK, Actual ${#VARIABLES_TO_CHECK[@]}
+             echo "  "CI_DOCKER_USER CI_DOCKER_PASSWORD required.
+             exit 1
+           fi
 
-        - run:
-           name: Docker push
-           command: |
-             docker login -u $CI_DOCKER_USER -p $CI_DOCKER_PASSWORD
-             BRANCH_SHORTEN=$(echo $CIRCLE_BRANCH | sed 's/[^-_.a-zA-Z0-9]/_/g')
-             TAG=${BRANCH_SHORTEN:0:12}-${CIRCLE_SHA1:0:4}
-             docker tag todayilearned $CI_DOCKER_USER/todayilearned:$TAG
-             docker tag todayilearned $CI_DOCKER_USER/todayilearned:latest
-             docker push $CI_DOCKER_USER/todayilearned
+      - run:
+         name: Docker push
+         command: |
+           docker login -u $CI_DOCKER_USER -p $CI_DOCKER_PASSWORD
+           BRANCH_SHORTEN=$(echo $CIRCLE_BRANCH | sed 's/[^-_.a-zA-Z0-9]/_/g')
+           TAG=${BRANCH_SHORTEN:0:12}-${CIRCLE_SHA1:0:4}
+           docker tag todayilearned $CI_DOCKER_USER/todayilearned:$TAG
+           docker tag todayilearned $CI_DOCKER_USER/todayilearned:latest
+           docker push $CI_DOCKER_USER/todayilearned
 
   deploy_to_stage:
-      docker:
-        - image: circleci/node:7.10
-      working_directory: ~/app
-      steps:
-        - attach_workspace:
-            at: ~/app
-        - setup_remote_docker:
-            docker_layer_caching: true
+    docker:
+      - image: circleci/node:7.10
+    working_directory: ~/app
+    steps:
+      - attach_workspace:
+          at: ~/app
+      - setup_remote_docker:
+          docker_layer_caching: true
 
-        - run:
-           name: Docker environment variables check
-           command: |
-             echo Docker environment variables check
-             NUM_OF_VARIABLES_TO_CHECK=6
-             VARIABLES_TO_CHECK=(\
-             $CI_STAGE_SSH_PEMURL \
-             "$CI_STAGE_SSH_FINGERPRINT" \
-             $CI_STAGE_SSH_USER \
-             $CI_STAGE_HOST \
-             $CI_STAGE_APP_PORT \
-             $CI_DOCKER_USER \
-             )
+      - run:
+         name: Docker environment variables check
+         command: |
+           echo Docker environment variables check
+           NUM_OF_VARIABLES_TO_CHECK=6
+           VARIABLES_TO_CHECK=(\
+           $CI_STAGE_SSH_PEMURL \
+           "$CI_STAGE_SSH_FINGERPRINT" \
+           $CI_STAGE_SSH_USER \
+           $CI_STAGE_HOST \
+           $CI_STAGE_APP_PORT \
+           $CI_DOCKER_USER \
+           )
 
-             if [ $NUM_OF_VARIABLES_TO_CHECK -ne ${#VARIABLES_TO_CHECK[@]} ]
-             then
-               echo "  "Add Environment Variables on ci environment.
-               echo "  "Number of variables. Expected $NUM_OF_VARIABLES_TO_CHECK, Actual ${#VARIABLES_TO_CHECK[@]}
-               echo "  "CI_STAGE_SSH_PEMURL CI_STAGE_SSH_FINGERPRINT CI_STAGE_SSH_USER \
-                 CI_STAGE_HOST CI_STAGE_APP_PORT CI_DOCKER_USER required.
-               exit 1
-             fi
+           if [ $NUM_OF_VARIABLES_TO_CHECK -ne ${#VARIABLES_TO_CHECK[@]} ]
+           then
+             echo "  "Add Environment Variables on ci environment.
+             echo "  "Number of variables. Expected $NUM_OF_VARIABLES_TO_CHECK, Actual ${#VARIABLES_TO_CHECK[@]}
+             echo "  "CI_STAGE_SSH_PEMURL CI_STAGE_SSH_FINGERPRINT CI_STAGE_SSH_USER \
+               CI_STAGE_HOST CI_STAGE_APP_PORT CI_DOCKER_USER required.
+             exit 1
+           fi
 
-        - run:
-            name: Deploy docker container on stage server
-            command: |
-              BRANCH_SHORTEN=$(echo $CIRCLE_BRANCH | sed 's/[^-_.a-zA-Z0-9]/_/g')
-              TAG=${BRANCH_SHORTEN:0:12}-${CIRCLE_SHA1:0:4}
+      - run:
+          name: Deploy docker container on stage server
+          command: |
+            BRANCH_SHORTEN=$(echo $CIRCLE_BRANCH | sed 's/[^-_.a-zA-Z0-9]/_/g')
+            TAG=${BRANCH_SHORTEN:0:12}-${CIRCLE_SHA1:0:4}
 
-              export DEPLOY_SSH_PEMURL=$CI_STAGE_SSH_PEMURL
-              export DEPLOY_SSH_FINGERPRINT=$CI_STAGE_SSH_FINGERPRINT
-              export DEPLOY_SSH_USER=$CI_STAGE_SSH_USER
-              export DEPLOY_SSH_HOST=$CI_STAGE_HOST
-              export DEPLOY_APP_PORT=$CI_STAGE_APP_PORT
-              export DOCKER_USER=$CI_DOCKER_USER
-              export DOCKER_TAG=$TAG
-              ./deploy-scripts/deploy.sh
+            export DEPLOY_SSH_PEMURL=$CI_STAGE_SSH_PEMURL
+            export DEPLOY_SSH_FINGERPRINT=$CI_STAGE_SSH_FINGERPRINT
+            export DEPLOY_SSH_USER=$CI_STAGE_SSH_USER
+            export DEPLOY_SSH_HOST=$CI_STAGE_HOST
+            export DEPLOY_APP_PORT=$CI_STAGE_APP_PORT
+            export DOCKER_USER=$CI_DOCKER_USER
+            export DOCKER_TAG=$TAG
+            ./deploy-scripts/deploy.sh
 
   deploy_to_prod:
-      docker:
-        - image: circleci/node:7.10
-      working_directory: ~/app
-      steps:
-        - attach_workspace:
-            at: ~/app
-        - setup_remote_docker:
-            docker_layer_caching: true
+    docker:
+      - image: circleci/node:7.10
+    working_directory: ~/app
+    steps:
+      - attach_workspace:
+          at: ~/app
+      - setup_remote_docker:
+          docker_layer_caching: true
 
-        - run:
-           name: Docker environment variables check
-           command: |
-             echo Docker environment variables check
-             NUM_OF_VARIABLES_TO_CHECK=6
-             VARIABLES_TO_CHECK=(\
-             $CI_PROD_SSH_PEMURL \
-             "$CI_PROD_SSH_FINGERPRINT" \
-             $CI_PROD_SSH_USER \
-             $CI_PROD_HOST \
-             $CI_PROD_APP_PORT \
-             $CI_DOCKER_USER \
-             )
+      - run:
+         name: Docker environment variables check
+         command: |
+           echo Docker environment variables check
+           NUM_OF_VARIABLES_TO_CHECK=6
+           VARIABLES_TO_CHECK=(\
+           $CI_PROD_SSH_PEMURL \
+           "$CI_PROD_SSH_FINGERPRINT" \
+           $CI_PROD_SSH_USER \
+           $CI_PROD_HOST \
+           $CI_PROD_APP_PORT \
+           $CI_DOCKER_USER \
+           )
 
-             if [ $NUM_OF_VARIABLES_TO_CHECK -ne ${#VARIABLES_TO_CHECK[@]} ]
-             then
-               echo "  "Add Environment Variables on ci environment.
-               echo "  "Number of variables. Expected $NUM_OF_VARIABLES_TO_CHECK, Actual ${#VARIABLES_TO_CHECK[@]}
-               echo "  "CI_PROD_SSH_PEMURL CI_PROD_SSH_FINGERPRINT CI_PROD_SSH_USER \
-                 CI_PROD_HOST CI_PROD_APP_PORT CI_DOCKER_USER required.
-               exit 1
-             fi
+           if [ $NUM_OF_VARIABLES_TO_CHECK -ne ${#VARIABLES_TO_CHECK[@]} ]
+           then
+             echo "  "Add Environment Variables on ci environment.
+             echo "  "Number of variables. Expected $NUM_OF_VARIABLES_TO_CHECK, Actual ${#VARIABLES_TO_CHECK[@]}
+             echo "  "CI_PROD_SSH_PEMURL CI_PROD_SSH_FINGERPRINT CI_PROD_SSH_USER \
+               CI_PROD_HOST CI_PROD_APP_PORT CI_DOCKER_USER required.
+             exit 1
+           fi
 
-        - run:
-            name: Deploy docker container on stage server
-            command: |
-              BRANCH_SHORTEN=$(echo $CIRCLE_BRANCH | sed 's/[^-_.a-zA-Z0-9]/_/g')
-              TAG=${BRANCH_SHORTEN:0:12}-${CIRCLE_SHA1:0:4}
+      - run:
+          name: Deploy docker container on stage server
+          command: |
+            BRANCH_SHORTEN=$(echo $CIRCLE_BRANCH | sed 's/[^-_.a-zA-Z0-9]/_/g')
+            TAG=${BRANCH_SHORTEN:0:12}-${CIRCLE_SHA1:0:4}
 
-              export DEPLOY_SSH_PEMURL=$CI_PROD_SSH_PEMURL
-              export DEPLOY_SSH_FINGERPRINT=$CI_PROD_SSH_FINGERPRINT
-              export DEPLOY_SSH_USER=$CI_PROD_SSH_USER
-              export DEPLOY_SSH_HOST=$CI_PROD_HOST
-              export DEPLOY_APP_PORT=$CI_PROD_APP_PORT
-              export DOCKER_USER=$CI_DOCKER_USER
-              export DOCKER_TAG=$TAG
-              ./deploy-scripts/deploy.sh
+            export DEPLOY_SSH_PEMURL=$CI_PROD_SSH_PEMURL
+            export DEPLOY_SSH_FINGERPRINT=$CI_PROD_SSH_FINGERPRINT
+            export DEPLOY_SSH_USER=$CI_PROD_SSH_USER
+            export DEPLOY_SSH_HOST=$CI_PROD_HOST
+            export DEPLOY_APP_PORT=$CI_PROD_APP_PORT
+            export DOCKER_USER=$CI_DOCKER_USER
+            export DOCKER_TAG=$TAG
+            ./deploy-scripts/deploy.sh
 
 workflows:
   version: 2
@@ -218,9 +272,19 @@ workflows:
             - react_lint_checks
             - react_tests
 
+      - express_install_dependencies
+      - express_lint_checks:
+          requires:
+            - express_install_dependencies
+      - express_tests:
+          requires:
+            - express_install_dependencies
+
       - docker_build_and_push:
           requires:
             - react_build
+            - express_lint_checks
+            - express_tests
 
       - deploy_to_stage:
           requires:
